# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PolicyGen < Formula
  desc "policy-gen is a utility that allows you to generate cloud policies from file markers."
  homepage "https://github.com/scottd018/policy-gen"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/scottd018/policy-gen/releases/download/v0.0.1/policy-gen_v0.0.1_Darwin_arm64.tar.gz"
      sha256 "759e1e4c7cbd8de9a1f089db9513af9104a32257abfca9d1f36759c3b1f2136c"

      def install
        bin.install "policy-gen"
        bash_completion.install "completions/policy-gen.bash" => "policy-gen"
        zsh_completion.install "completions/policy-gen.zsh" => "_policy-gen"
        fish_completion.install "completions/policy-gen.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/scottd018/policy-gen/releases/download/v0.0.1/policy-gen_v0.0.1_Darwin_x86_64.tar.gz"
      sha256 "9060ec8992de34cf735fdc354a9ed042f6765c3f9be026b2641539d4400c2d6a"

      def install
        bin.install "policy-gen"
        bash_completion.install "completions/policy-gen.bash" => "policy-gen"
        zsh_completion.install "completions/policy-gen.zsh" => "_policy-gen"
        fish_completion.install "completions/policy-gen.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scottd018/policy-gen/releases/download/v0.0.1/policy-gen_v0.0.1_Linux_arm64.tar.gz"
      sha256 "76f11ff96f78318303794a60f7c0ceaf7b4edc12dc66eac0cc84de84f6b74abb"

      def install
        bin.install "policy-gen"
        bash_completion.install "completions/policy-gen.bash" => "policy-gen"
        zsh_completion.install "completions/policy-gen.zsh" => "_policy-gen"
        fish_completion.install "completions/policy-gen.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/scottd018/policy-gen/releases/download/v0.0.1/policy-gen_v0.0.1_Linux_x86_64.tar.gz"
      sha256 "170c841e4a1c34129547fe4432c440b0a1ab500d0a88d15468cc596eb256b528"

      def install
        bin.install "policy-gen"
        bash_completion.install "completions/policy-gen.bash" => "policy-gen"
        zsh_completion.install "completions/policy-gen.zsh" => "_policy-gen"
        fish_completion.install "completions/policy-gen.fish"
      end
    end
  end

  test do
    system "#{bin}/policy-gen version"
  end
end
