# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PolicyGen < Formula
  desc "policy-gen is a utility that allows you to generate cloud policies from file markers."
  homepage "https://github.com/scottd018/policy-gen"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/scottd018/policy-gen/releases/download/v0.0.1/policy-gen_0.0.1_darwin_arm64.tar.gz"
      sha256 "72de7a7aefff0df4d47e685f69ce47d59019811a5c27c535f69d0500abeb5ed0"

      def install
        bin.install "policy-gen"
        bash_completion.install "completions/policy-gen.bash" => "policy-gen"
        zsh_completion.install "completions/policy-gen.zsh" => "_policy-gen"
        fish_completion.install "completions/policy-gen.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/scottd018/policy-gen/releases/download/v0.0.1/policy-gen_0.0.1_darwin_amd64.tar.gz"
      sha256 "ca8015d40cad1692239b3032255aef01e8118991f7c052cbdbcd4564450fef76"

      def install
        bin.install "policy-gen"
        bash_completion.install "completions/policy-gen.bash" => "policy-gen"
        zsh_completion.install "completions/policy-gen.zsh" => "_policy-gen"
        fish_completion.install "completions/policy-gen.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scottd018/policy-gen/releases/download/v0.0.1/policy-gen_0.0.1_linux_arm64.tar.gz"
      sha256 "62875f359d531a5ac5a485c99011afb97a74acfd8d0e16a4fb6c36b36d3bede6"

      def install
        bin.install "policy-gen"
        bash_completion.install "completions/policy-gen.bash" => "policy-gen"
        zsh_completion.install "completions/policy-gen.zsh" => "_policy-gen"
        fish_completion.install "completions/policy-gen.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/scottd018/policy-gen/releases/download/v0.0.1/policy-gen_0.0.1_linux_amd64.tar.gz"
      sha256 "899a587da1735df273490894e388cf651d7770ca223883468a121139aa6c5285"

      def install
        bin.install "policy-gen"
        bash_completion.install "completions/policy-gen.bash" => "policy-gen"
        zsh_completion.install "completions/policy-gen.zsh" => "_policy-gen"
        fish_completion.install "completions/policy-gen.fish"
      end
    end
  end

  test do
    system "#{bin}/policy-gen version"
  end
end
