# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PolicyGen < Formula
  desc "policy-gen is a utility that allows you to generate cloud policies from file markers."
  homepage "https://github.com/scottd018/policy-gen"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scottd018/policy-gen/releases/download/v0.0.1/policy-gen_v0.0.1Darwin_x86_64.tar.gz"
      sha256 "45243f487d11aa305003e468cb9d383bfe2f9c2422021a6a6ace24af9d47c546"

      def install
        bin.install "policy-gen"
        bash_completion.install "completions/policy-gen.bash" => "policy-gen"
        zsh_completion.install "completions/policy-gen.zsh" => "_policy-gen"
        fish_completion.install "completions/policy-gen.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scottd018/policy-gen/releases/download/v0.0.1/policy-gen_v0.0.1Darwin_arm64.tar.gz"
      sha256 "24f256c48143a1e8bb05cd0b6db37a7fcd9da84670132ea59268aed5d54b1a54"

      def install
        bin.install "policy-gen"
        bash_completion.install "completions/policy-gen.bash" => "policy-gen"
        zsh_completion.install "completions/policy-gen.zsh" => "_policy-gen"
        fish_completion.install "completions/policy-gen.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scottd018/policy-gen/releases/download/v0.0.1/policy-gen_v0.0.1Linux_arm64.tar.gz"
      sha256 "fc6931704cd653f9c53c457cc4e18a92461dbda5272f395df6296c4e9696f8c3"

      def install
        bin.install "policy-gen"
        bash_completion.install "completions/policy-gen.bash" => "policy-gen"
        zsh_completion.install "completions/policy-gen.zsh" => "_policy-gen"
        fish_completion.install "completions/policy-gen.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/scottd018/policy-gen/releases/download/v0.0.1/policy-gen_v0.0.1Linux_x86_64.tar.gz"
      sha256 "b3ce5fbafd6a04fbae3f9b04eea043072935b919d50b31b6249eed223f4f8523"

      def install
        bin.install "policy-gen"
        bash_completion.install "completions/policy-gen.bash" => "policy-gen"
        zsh_completion.install "completions/policy-gen.zsh" => "_policy-gen"
        fish_completion.install "completions/policy-gen.fish"
      end
    end
  end

  test do
    system "#{bin}/policy-gen version"
  end
end
